### PR TITLE
Update graphics device properly when size/resolution changes.

### PR DESCRIPTION
**Pull request by huguesv**
Fixes https://github.com/Microsoft/RTVS/issues/2017

Test will be added (in RTVS repo)

### CODE REVIEW

**Comment by int19h** [comment]
:+1:

**Comment by karthiknadig** [comment]
:+1:

**Comment by huguesv** [comment]
Don't merge, I'm almost certain this will be unnecessary.

**Comment by huguesv** [comment]
This change will be part of the multi-plot window support PR.

**Pull request closed without merging**
